services:
  - type: web
    name: wonderbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.kidapp.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false 