name: WonderBot CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  judgeval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          pip install "git+https://${GITHUB_TOKEN}:x-oauth-basic@github.com/judgeval/judgeval.git" requests

      - name: Start backend
        run: |
          uvicorn src.kidapp.api:app --host 0.0.0.0 --port 8000 &
          sleep 10  # Wait for server to start

      - name: Generate answers
        run: python generate_answers.py

      - name: Run Judgeval
        run: judgeval evaluate --input wonderbot_outputs.csv --criteria criteria.yaml --output judgeval_results.csv

      - name: Check Judgeval results
        run: |
          if grep -q "NO" judgeval_results.csv; then
            echo "❌ Some answers failed the evaluation!"
            exit 1
          else
            echo "✅ All answers passed Judgeval evaluation."
          fi

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":x: WonderBot CI failed!\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nSee details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": ":white_check_mark: WonderBot CI passed!\nRepo: ${{ github.repository }}\nBranch: ${{ github.ref }}\nCommit: ${{ github.sha }}\nSee details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 